"""Add state, country, pincode, telephone, mobile, bank_name, account_no, ifsc_code

Revision ID: f11a69acff01
Revises: 
Create Date: 2025-08-28 18:08:07.987898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11a69acff01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pincode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('telephone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mobile', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_no', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ifsc_code', sa.String(length=50), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('gst_no',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('contact_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_no', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('gst_no',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('ifsc_code')
        batch_op.drop_column('account_no')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('mobile')
        batch_op.drop_column('telephone')
        batch_op.drop_column('pincode')
        batch_op.drop_column('country')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
